USE nttdata_javajdbc;

DROP TABLE spring3_customer;

CREATE TABLE spring_customer (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    LASTNAME1 VARCHAR(50) NOT NULL,
    LASTNAME2 VARCHAR(50) NOT NULL,
    IDN VARCHAR(9) NOT NULL UNIQUE,
    BIRTH_DATE DATE NOT NULL,
    PRIMARY KEY (ID)
);